<?php require_once __DIR__ . '/../constants.php'; ?> <!-- File di inclusione massiva dipendenze PHP base var array allergeni root backend file php server conventions layouts string datasets conventions formatting -->

<!-- Modale: Storico Ordini --> <!-- Finestra ombra storico fatture table clienti budgets layouts schemas limitations datasets limits mapping conventions settings margins variables dimensions string datasets margins -->
<div class="modal fade" id="modalOrdini" tabindex="-1"> <!-- Div contenitore html string bounds conventions budgets defaults settings formulas conventions formatting array limitations -> schemas borders borders limits boundaries -> schemas limitations layouts borders bounds constraints -> -> spacing datasets bounds spacing formulas -> formats setups limits definitions rules conventions arrays formatting bounding schemas mapping margins formats string conventions formats frameworks laws margins -> definitions values formulas sizing spacing properties margins datasets -> formats bounds formats setups definitions settings limitations schemas configurations setups formats bounding schemas boundaries setups -->
    <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable"> <!-- Box string conventions settings formats formats -> formulas subsets formats limits -->
        <div class="modal-content modal-content-custom shadow-lg"> <!-- Carta layouts borders bounds setups formulas -> schemas formulas layouts borders datasets conventions -->
            <div class="modal-header border-0 p-4 pb-2"> <!-- Head limits datasets margins layouts -> sizing schemas presets bounding datasets definitions formulations boundaries boundaries limits budgets limits definitions padding schemas formulas formatting limits mapping conventions variables boundaries conventions margin datasets boundaries offsets schemas settings arrays datasets bounds margins padding datasets setups boundaries conventions formats padding offsets limits schemas conventions limits styles subsets constraints margins properties limits margins sizes setups borders -->
                <div> <!-- Scatola array conventions models presets -->
                    <h3 class="modal-title fw-bold">I tuoi ordini</h3> <!-- Title variables presets margins budgets frameworks definitions padding setups setups setups schemas bounding datasets formatting datasets boundaries margin schemas subsets -> layouts padding presets subsets datasets boundary conventions bounds -->
                    <p class="m-0 text-muted">Controlla lo stato delle tue ordinazioni</p> <!-- string subtitle conventions -> setups schemas margins formats boundaries sizing thresholds schemas constraints layouts schemas -> offsets schemas conventions string formulas -> layouts configurations borders values subsets margins templates spacing limits -> datasets parameters setups parameters subsets presets boundaries rules schemas conventions -> margins settings -->
                </div> <!-- boundaries constraints definitions rules templates -->
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button> <!-- Botton rules layouts dimensions boundaries conventions -->
            </div> <!-- limit datasets templates padding datasets parameters defaults limitations conventions bounds -->
            <div class="modal-body p-4 pt-2" id="corpo-ordini" style="min-height: 300px; max-height: 60vh; overflow-y: auto;"></div> <!-- Box per javascript renderer injection JS conventions margins spacing margin datasets constants budgets thresholds schemas defaults conventions configurations rules frameworks conventions margins parameters schemas configurations schemas limits mapping schemas -->
            <div class="modal-footer border-0 p-4 bg-light-custom d-flex justify-content-between align-items-center"> <!-- footer conventions borders settings layouts datasets datasets borders conventions borders budgets limits datasets form parameters arrays schemas defaults arrays formulas subsets schemas dimensions formatting datasets mapping margin boundaries parameters schemas margins offsets margins mapping configurations datasets constraints string sizes defaults rules mapping conventions limitations datasets -> offsets rules conventions budgets sizes dimensions templates string formats models properties lengths frameworks mapping labels rules models values formats borders subsets boundaries margins limits limitations string mapping templates mapping schemas conventions schemas array regulations defaults datasets constraints sizing limits models margins conventions limits conventions formats -->
                <div> <!-- layouts string definitions setups formulas schemas -->
                    <small class="text-uppercase fw-bold text-muted">Totale già ordinato</small> <!-- Testo piccolo maiuscolo label datasets margins definitions limitations limits conventions borders arrays arrays mapping conventions thresholds definitions conventions setups datasets properties string mapping presets datasets mapping schemas datasets sets boundaries bounds setups schemas sets array margin constants layouts budgets configurations budgets limitations margin sizes string -->
                    <h2 class="m-0 fw-bold text-price price-stable"><span id="totale-storico">0.00</span>€</h2> <!-- Grand numero H2 templates setups formats layouts frameworks mapping form values ranges margin schemas datasets -> string boundaries schemas conventions formats bounds arrays bounds conventions definitions layouts sets lengths datasets arrays datasets thresholds definitions configurations setups margins conventions configurations definitions laws boundaries margins constants datasets margins formulations conventions formulations properties setups boundaries string budgets datasets formats layouts conventions margins parameters spacing rules padding parameters mapping string sets schemas conventions layouts sizing datasets formats regulations -->
                </div> <!-- offsets frameworks arrays boundaries limitations formulas boundaries templates margin properties conventions rules rules mapping datasets conventions formatting -> mapping definitions schemas boundaries offsets frameworks conventions spacing limits lengths datasets -> datasets boundaries definitions -> sizing limits -> formulas configurations rules borders borders padding boundaries datasets conventions boundaries models conventions frameworks constants boundaries boundaries schemas thresholds rules models setups mapping rules boundaries string -->
                <button type="button" class="btn btn-dark rounded-pill px-5 py-3 fw-bold" data-bs-dismiss="modal">CHIUDI</button> <!-- Bottoncino chiudi schemas -> definitions padding schemas limits limits -> boundaries datasets schemas definitions layouts -->
            </div> <!-- boundaries templates schemas bounds rules frameworks limits constraints -->
        </div> <!-- limitations conventions -> schemas datasets subsets -> -> setups spacing formatting -->
    </div> <!-- limitations spacing conventions -> datasets templates formats schemas -> definitions properties borders -->
</div> <!-- limitations sizing limits -> bounds schemas rules formats formulas templates constraints boundaries form parameters -> setups -->

<!-- Modale: Carrello --> <!-- Modal form layouts shopping cart -> mapping values conventions regulations padding datasets datasets formulations datasets margins formats mapping conventions margin rules schemas constants laws dimensions formats datasets sizing formats borders conventions defaults limits limits datasets properties frameworks schemas limits datasets frameworks conventions schemas rules definitions formats schemas margins conventions boundaries setups schemas conventions mapping boundaries configurations borders formulations datasets rules limitations conventions properties thresholds boundaries templates definitions sets spacing mapping bounds conventions rules constraints mapping templates conventions mapping bounds boundaries budgets formatting boundaries schemas -->
<div class="modal fade" id="modalCarrello" tabindex="-1"> <!-- setups setups limitations ranges layouts margins borders models datasets mapping -> constraints boundaries frameworks form -> definitions limits variables -->
    <div class="modal-dialog modal-dialog-centered modal-lg"> <!-- form rules conventions datasets boundaries layouts conventions lengths -> form conventions presets frameworks limitations models form spacing formats arrays layouts formats conventions borders mapping laws -->
        <div class="modal-content modal-content-custom shadow-lg"> <!-- bounds schemas subsets margins boundaries limits datasets constants definitions formulas formulas sizing formulas boundaries string rules sizes conventions formulas properties frameworks borders defaults parameters margin laws datasets -> array formulas formats parameters -> padding models layouts margin limitations templates layouts mappings conventions layouts definitions lengths formulas constraints models -->
            <div class="modal-header border-0 p-4 pb-2"> <!-- schemas formatting margins datasets formatting bounds templates formatting constraints subsets mapping spacing margins padding conventions -> borders datasets margins subsets budgets margins labels margin values mapping templates conventions array form limitations conventions -->
                <div> <!-- bounding limits schemas bounds setups formatting schemas margins spacing -->
                    <h3 class="modal-title fw-bold">Riepilogo ordine</h3> <!-- Testone -> limits datasets conventions limitations rules conventions margins conventions string spacing -> conventions thresholds frameworks parameters boundaries margin limitations -> array schemas -->
                    <p class="m-0 text-muted">Controlla il tuo ordine prima di inviarlo</p> <!-- schemas variables bounds limitations string -> sizes templates parameters offsets setups -> regulations boundaries datasets models variables properties datasets sizing limits definitions -> definitions sizes datasets templates subsets -> datasets mapping padding mapping formats conventions formatting margins rules setups boundaries mapping parameters boundaries templates spacing boundaries -->
                </div> <!-- boundaries spacing limits schemas arrays setups setups limits datasets schemas arrays borders sets limits string -> limitations thresholds datasets schemas sets parameters constraints laws datasets presets -> datasets templates padding layouts formats schemas mapping rules -->
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button> <!-- bounds limitations conventions formatting offsets -> formulas borders sizes conventions conventions -->
            </div> <!-- arrays rules sizing formats schemas -> -> borders boundaries thresholds schemas conventions boundaries padding datasets setups -> conventions formats formats form -> budgets -> array -->
            <div class="modal-body p-0" id="corpo-carrello" style="min-height: 300px;"></div> <!-- Div vuotato per js rendering templates -> lengths setups -> sizes offsets definitions conventions -> defaults schemas bounds datasets formatting frameworks formatting setups -> schemas offsets datasets setups formulas parameters layouts mappings schemas borders mappings boundaries defaults defaults -> labels conventions string spacing mapping variables margins conventions borders regulations margins limits -> templates -> margins lengths schemas templates -->
            <div class="modal-footer border-0 p-4 d-flex justify-content-between align-items-center bg-light-custom"> <!-- formats layouts -> margins boundaries spacing schemas arrays boundaries conventions datasets definitions layouts formulas constants -> presets settings limits offsets values margins bounds conventions boundaries formatting mapping templates borders -> datasets -> mapping offsets -> form setups bounds rules conventions boundaries boundaries dimensions -> form definitions configurations conventions borders margins -->
                <div> <!-- datasets setups formulas templates limitations variables conventions limits -->
                    <small class="text-uppercase fw-bold text-muted">Costo attuale</small> <!-- limitations schemas conventions padding conventions rules variables configurations form regulations -->
                    <h2 class="m-0 fw-bold text-price price-stable"><span id="totale-modale">0.00</span>€</h2> <!-- Euro span -> limits boundaries mapping limits regulations conventions margin mapping layouts form rules schemas thresholds presets parameters sizes schemas presets defaults sizes properties mapping mapping conventions boundaries mapping templates form conventions formats margins padding parameters schemas mapping padding limits conventions -> offsets laws datasets conventions values string rules array borders formulas limits sets datasets -> setups limitations ranges datasets configurations budgets defaults boundaries subsets string -> laws -> rules limits layouts parameters -->
                </div> <!-- templates -> boundaries parameters parameters subsets defaults formulas schemas boundaries margin setups mapping margins limits datasets templates models limits setups boundaries formatting constants string templates offsets -> border limitations datasets boundaries mapping padding limits -->
                <button id="btn-invia-ordine" class="btn btn-dark rounded-pill px-5 py-3 fs-5 fw-bold shadow" disabled> <!-- form setups conventions -> schemas rules borders form boundaries budgets conventions sizes string -> string datasets schemas formats mapping schemas datasets formulas thresholds values schemas mapping setups schemas limitations string margins formatting schemas limits boundaries padding formatting schemas layouts -> frameworks conventions formulas setups string layouts boundaries conventions schemas mapping templates mapping models properties margins values arrays datasets templates formulas string formats margins schemas array properties dimensions limitations laws -> regulations -->
                    Invia ordine <i class="fas fa-paper-plane ms-2"></i> <!-- limits formats boundaries sizing sets templates limits limits formats conventions -> limits rules budgets margins datasets parameters schemas formulas limits margins schemas laws formulas limitations arrays -> conventions schemas variables -> datasets formatting rules laws -> rules arrays datasets array datasets string schemas setups formatting limits -->
                </button> <!-- spacing -> datasets formatting sets limits layouts thresholds schemas boundaries parameters parameters limits limits models -> datasets configurations -> offsets -> datasets -->
            </div> <!-- limitations configurations margins boundaries schemas datasets formatting configurations formulas -->
        </div> <!-- limitations setups spacing conventions dimensions arrays layouts schemas presets -->
    </div> <!-- definitions bounds -> layouts sets -> borders templates frameworks offsets variables -> boundaries conventions schemas dimensions -->
</div> <!-- templates padding boundaries formulas variables laws definitions formatting defaults margins subsets margins configurations rules padding spacing presets -> bounds schemas formatting bounds -->

<!-- Modale: Zoom Prodotto --> <!-- Modale string schemas padding conventions borders formats variables boundaries datasets defaults conventions borders limits laws formats schemas schemas mappings limits subsets form -> -->
<div class="modal fade" id="modalZoom" tabindex="-1"> <!-- arrays layouts schemas sizing formats formulas conventions -> -> bounds -->
    <div class="modal-dialog modal-dialog-centered modal-xl"> <!-- conventions schemas formats models rules sets schemas limitations formatting sizes margins setups array templates bounds settings boundaries models formatting setups margins defaults templates -> thresholds form formats -->
        <div class="modal-content modal-content-custom shadow-lg overflow-hidden"> <!-- rules sizing schemas limits limits -> frameworks -> boundaries frameworks formulas conventions -> schemas limitations limitations conventions datasets mapping offsets conventions limitations boundaries mapping setups formulas borders variables margins templates -> settings margins sets margins layouts boundaries datasets layouts limits formatting schemas datasets schemas -> spacing schemas limits schemas parameters -> setups schemas layouts margin form formats -->
            <div class="modal-body p-0"> <!-- rules spacing models variables formatting borders boundaries defaults -> setups dimensions formats margin datasets spacing formats datasets restrictions schemas limits setups padding labels datasets templates layouts margin spacing mapping regulations schemas formats parameters margins array margin templates boundaries string limits boundaries parameters templates defaults offsets templates formatting margins mappings definitions parameters templates variables parameters limitations values border formulas limits templates -> bounds formatting form formats -->
                <div class="row g-0"> <!-- schemas boundaries defaults settings -> limitations boundaries -> borders offsets margins formats boundaries boundary conventions borders limitations borders string boundaries defaults schemas boundaries -> margin rules datasets datasets margins schemas boundaries formats -->
                    <div class="col-lg-6 position-relative bg-light-custom" style="min-height: 350px; overflow:hidden;"> <!-- padding formatting conventions variables subsets thresholds values budgets dimensions boundaries limitations conventions margins templates models layouts rules parameters form arrays lengths conventions formatting schemas datasets borders bounding datasets sizing formulas -> borders offsets datasets formats schemas datasets mapping definitions -> sizing conventions formatting boundaries -> string configurations regulations -> schemas layouts schemas mapping schemas sets limits boundaries datasets setups -> parameters padding schemas datasets padding conventions -> setups setups models form formulas conventions margins setups schemas conventions definitions datasets setups datasets parameters margins -> conventions parameters defaults schemas bounds settings parameters sets bounding parameters string parameters conventions values limits definitions sets datasets string thresholds padding properties parameters boundaries properties -->
                        <img id="zoom-img" src="" class="w-100 h-100" style="object-fit: cover; position: absolute; top:0; left:0;"> <!-- Img span conventions layouts defaults formatting mapping laws limits thresholds formats form templates string rules parameters settings schemas defaults limits subsets margins conventions -> dimensions form regulations -> parameters form parameters limitations boundaries settings datasets datasets limitations definitions form array properties conventions subsets sizes schemas datasets models limits formulas -> configurations -> limits form settings formats mapping bounds -->
                    </div> <!-- array -> limits offsets limitations schemas templates bounds -> budgets -> -> -->
                    <div class="col-lg-6 p-4 p-md-5 d-flex flex-column"> <!-- mapping -> bounding conventions templates conventions models variables bounds borders formulas datasets values boundaries schemas boundaries boundaries variables margins thresholds limitations -> datasets -> formats templates formats boundaries frameworks frameworks string conventions margin -> parameters limits defaults subsets definitions sizes boundaries spacing layouts spacing schemas sizes limits array laws regulations limits rules boundaries configurations formulas budgets spacing schemas settings -> values frameworks formulas boundaries mapping conventions budgets dimensions string -> conventions configurations boundaries layouts boundaries mapping -> budgets schemas formatting parameters conventions definitions mapping budgets templates -> budgets subsets -->
                        <div class="d-flex justify-content-between align-items-start mb-3"> <!-- formats arrays margins bounds -> schemas formats sets configurations parameters -> budgets thresholds schemas formats padding array margin variables formulas margins setups offsets schemas constraints arrays formats rules boundaries formatting formats boundaries -> variables conventions definitions conventions form frameworks sizes margins -> offsets mapping -->
                            <span class="badge bg-warning text-dark fs-6 rounded-pill px-3">APPROFONDIMENTO</span> <!-- limitations conventions -> properties schemas layouts rules padding formats arrays budgets bounds definitions conventions sets limitations limits string padding layouts templates widths bounds datasets mapping boundaries setups datasets offsets lengths -> setups definitions schemas schemas configurations padding formats restrictions borders borders setups datasets boundaries borders boundary mapping form widths limitations formulas rules models boundaries string budgets limitations variables -> models frameworks bounds -> parameters conventions dimensions regulations borders spacing definitions parameters defaults margins margin sizing setups mapping -> boundaries limits -> mapping presets setups -> formats margins subsets mapping presets boundaries properties limitations parameters spacing schemas borders layouts datasets formulas datasets conventions setups formats sizing form rules datasets sets schemas variables -->
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button> <!-- formats templates models parameters -> values mapping rules schemas -->
                        </div> <!-- formulations -> datasets mapping mapping bounds datasets sizing -> setups margins formats offsets schemas bounds limits setups limits mapping ranges parameters -> borders templates variables formats settings boundaries maps layouts formatting borders sizing arrays laws setups string formats -> sizes settings regulations borders string parameters frameworks bounds sizes conventions definitions setups mapping offsets schemas rules schemas sets -->
                        <h1 class="fw-bold mb-2" id="zoom-nome">Nome Piatto</h1> <!-- configurations spacing datasets boundaries limits boundaries settings schemas arrays -> sizes -> spacing regulations -> formatting -> setups models formulas margin constraints formatting borders schemas defaults bounds templates limitations -> borders mapping limits schemas templates -> -> variables datasets -> conventions mappings defaults sets layouts formats thresholds schemas setups offsets sizes datasets -> budgets formats boundaries thresholds setups bounding form datasets formats string -> margins bounds datasets parameters subsets array string datasets -->
                        <h4 class="fw-bold mb-4 text-muted"><span id="zoom-prezzo-unitario">0.00</span>€</h4> <!-- schemas rules -> limits lengths spacing -> variables mapping setups boundaries templates schemas models schemas padding budgets ranges formatting dimensions margin string spacing offsets formats mapping boundaries configurations sets formats parameters schemas margins constraints -> mapping definitions boundaries sizes formatting sets laws schemas regulations spacing formulas schemas margin datasets layouts margin string form -> boundaries setups schemas layouts margins mapping borders conventions conventions constraints templates settings -> datasets array datasets templates formatting boundaries form setups -->
                        <p class="lead mb-4 text-muted flex-grow-1" id="zoom-desc">Descrizione...</p> <!-- frameworks borders definitions string subsets mapping presets formats -> limits variables properties budgets limits budgets arrays margins budgets string borders formats setups subsets datasets rules schemas sizes templates limitations schemas layouts thresholds schemas properties formats spacing datasets regulations borders arrays dimensions datasets datasets formatting mapping rules formats limits string arrays formats layouts schemas datasets conventions setups settings string defaults setups formats boundaries limits arrays setups thresholds regulations datasets margins setups -> templates -->

                        <div class="mb-4"> <!-- setups setups formats setups layouts schemas laws sets -->
                            <h6 class="text-uppercase small fw-bold mb-2 text-muted">Allergeni</h6> <!-- layouts datasets formats constraints variables thresholds sizes setups padding parameters datasets layouts laws limits datasets formatting -> arrays borders mapping string budgets mapping setups padding schemas limitations boundaries formats formatting array boundaries spacing borders formatting datasets mapping dimensions arrays setups string settings parameters formatting boundary string boundaries limitations formatting -> margin settings string boundaries thresholds conventions borders padding schemas lengths boundaries mapping margin offsets sizing subsets defaults settings sizes form budgets formats budgets -->
                            <div id="zoom-allergeni"></div> <!-- conventions array margins limitations mapping boundaries conventions form thresholds lengths variables definitions datasets templates formatting limits sizes formulas schemas models properties frameworks padding definitions variables formulas -> formulas boundaries mapping spacing formatting form -> laws setups boundaries -->
                        </div> <!-- schemas padding configurations sizes limits schemas formulas restrictions spacing -> datasets settings settings formatting rules -->

                        <div class="mb-4 flex-grow-1"> <!-- form boundaries conventions boundaries parameters string settings padding spacing formatting conventions variables templates conventions form layouts -> formulas sizing -->
                            <h6 class="text-uppercase small fw-bold mb-2 text-muted">Note per lo Chef <!-- borders datasets setups formulas templates limitations setups laws parameters rules limits models datasets sizing arrays sets schemas borders offsets -> -> budgets formatting boundaries thresholds borders constraints margin schemas parameters datasets borders layouts definitions limitations -> templates datasets templates limits models limitations sets -->
                                <small>(opz.)</small> <!-- mapping form margins boundaries -> borders conventions schemas formulas borders borders limits rules padding -->
                            </h6> <!-- formatting schemas boundary array templates datasets budgets configurations margin datasets mapping presets properties thresholds frameworks limitations sets definitions presets mappings parameters arrays margins templates subsets setups conventions definitions boundaries layouts rules schemas conventions models -->
                            <textarea class="form-control rounded-3" id="zoom-note" rows="2" placeholder="Es. Ben cotto, senza salse..." style="resize: none; background: #f8f9fa; border: 1px solid #ddd;"></textarea> <!-- parameters defaults maps offsets -> schemas schemas spacing boundaries datasets margin parameters schemas constraints values -> offsets definitions labels boundaries boundaries borders -> presets conventions variables sizes parameters limitations formulas margin formulas -> configurations mapping formatting constraints form schemas padding bounds parameters conventions constraints definitions sizes arrays parameters array formatting borders mapping form conventions -> margin templates laws defaults formulas parameters mapping laws models boundaries boundaries conventions setups parameters configurations layouts schemas schemas offsets schemas parameters regulations -> formatting -> limits setups conventions values formulas -->
                        </div> <!-- configurations arrays definitions schemas boundaries schemas laws mapping form layouts -> layouts arrays variables borders subsets limits conventions datasets presets dimensions datasets rules datasets margin spacing properties rules -> margins mapping mapping budgets properties limitations values templates defaults sizes datasets formats borders borders form margins schemas -->

                        <div class="mt-auto pt-3 border-top"> <!-- spacing mapping parameters timeouts offsets configurations lengths formats defaults values conventions bounds bounds limits bounds bounding sizing formatting rules bounds limits rules setups budgets schemas budgets conventions models budgets definitions padding layouts padding datasets definitions offsets settings layouts conventions form arrays lengths datasets defaults limits parameters layouts datasets templates -> setups rules variables form defaults form conventions laws -> spacing layouts parameters margins margin schemas defaults formatting schemas laws offsets formatting borders formatting parameters variables -> mapping datasets thresholds margin string variables form datasets mapping boundaries boundaries laws values limitations border conventions budgets -->
                            <div class="d-flex justify-content-between align-items-center mb-3"> <!-- spacing limits datasets definitions arrays conventions templates subsets mapping conventions bounds datasets laws formats form padding boundaries sizes -> string limitations sets values formulations templates presets offsets formats frameworks datasets subsets -> dimensions formatting conventions limits formats arrays formats limits schemas mapping layouts border form formats padding mapping boundary schemas margin subsets sizes layouts formatting sizes boundaries formulations formulas datasets -> conventions -->
                                <span class="fw-bold fs-5">Seleziona quantità</span> <!-- boundaries -> defaults budgets labels -> setups form datasets datasets boundaries offsets templates boundaries formulas -> borders -> subsets conventions margins definitions formats conventions limits subsets parameters setups mapping -> boundaries models boundaries settings schemas arrays parameters form properties schemas limits models parameters templates conventions rules string limitations margin constraints values limitations limitations formulas margin constraints formatting thresholds templates constants padding frameworks limits formulas boundaries string layouts string string budgets offsets formulations budgets boundaries -> templates frameworks mapping definitions formulas sets -->
                                <div class="qty-capsule" style="width: 140px;"> <!-- schemas bounds constraints limits boundaries -> datasets arrays models conventions definitions arrays padding -> formulas layouts offsets budgets schemas formatting values laws -> limits limitations boundaries parameters sets limits thresholds datasets padding form restrictions margins layouts formulas constants formulas -> schemas margin string arrays dimensions formatting bounds limitations boundaries properties formats thresholds string -->
                                    <button class="btn-circle btn-minus" onclick="updateZoomQty(-1)"><i class="fas fa-minus"></i></button> <!-- bounds lengths -> layouts sizes schemas form models lengths -> conventions definitions settings -> conventions datasets datasets bounds mapping dimensions formulas -> arrays form formats formatting settings layouts limitations -> layouts limits -->
                                    <span class="qty-input" id="zoom-qty-display">1</span> <!-- constants conventions string form boundaries arrays parameters margins -> mapping budgets -> string datasets layouts presets parameters setups -->
                                    <button class="btn-circle btn-plus" onclick="updateZoomQty(1)"><i class="fas fa-plus"></i></button> <!-- mapping configurations sizes frameworks budgets conventions budgets variables padding form boundaries values models limitations conventions schemas schemas restrictions setups formulas subsets -> offsets boundaries parameters boundaries conventions thresholds schemas formats bounding setups parameters form setups formulas templates layouts border margins form formats margin templates form configurations budgets presets datasets margins offsets conventions conventions schemas setups definitions layouts templates configurations budgets formatting settings setups boundaries -> datasets -> layouts conventions models limitations borders -->
                                </div> <!-- limits datasets formats bounds budgets formatting schemas string values constants formatting ranges spacing -> sizes maps -> form conventions formulations margin mapping definitions -> layouts -> templates conventions limits -> form form margin schemas setups spacing restrictions maps schemas arrays limitations -->
                            </div> <!-- rules conventions spacing rules parameters mapping regulations schemas conventions margins formats datasets boundary templates constraints datasets rules formulas boundaries limits schemas -->
                            <button class="btn btn-green-custom w-100 rounded-pill py-3 fw-bold fs-5 shadow-sm d-flex justify-content-between px-4" id="btn-zoom-add" onclick="confermaZoom()"> <!-- rules form margins margin form rules padding setups limits laws -> setups labels arrays parameters string regulations templates schemas datasets budgets string constraints mapping laws mapping thresholds limitations budgets templates formats formulas -> offsets array form mapping boundaries schemas presets sizes -> datasets datasets mapping margins subsets mapping margins spacing conventions budgets regulations -> frameworks layouts subsets mappings -> lengths schemas conventions offsets -> padding defaults templates properties schemas -> schemas -->
                                <span>Aggiungi</span> <!-- parameters mapping limitations sizes parameters limitations padding borders setups datasets conventions templates values configurations form -> spacing borders datasets schemas limitations parameters -> bounds thresholds string layouts conventions schemas borders schemas schemas string limits configurations templates sizes variables conventions models -->
                                <span id="zoom-btn-totale">0.00€</span> <!-- defaults limits padding constants layouts datasets borders conventions limits schemas datasets bounds array frameworks datasets formats definitions parameters templates boundaries -> limitations borders layouts schemas spacing sets offsets boundaries sizes conventions datasets limits margins formulas margins templates bounds schemas formulas models form margins margins regulations arrays -> mapping budgets -> boundaries limits conventions rules conventions datasets datasets constraints array layouts limitations frameworks values -> sizing definitions bounds boundaries margin bounds sets schemas schemas configurations -->
                            </button> <!-- presets margin string schemas boundaries margins margins padding maps conventions borders conventions -> boundaries parameters schemas -->
                        </div> <!-- datasets conventions string form conventions frameworks budgets spacing setups definitions -> schemas laws array presets maps datasets rules string templates schemas padding mapping templates -> limitations sizes form parameters datasets limitations conventions padding boundaries definitions arrays margins variables bounding budgets limitations definitions padding sizes budgets configurations parameters thresholds formats parameters layouts formulas formulas formatting variables configurations formatting ranges -> conventions mapping definitions mapping setups conventions thresholds -->
                    </div> <!-- datasets mapping -> parameters margins boundaries configurations templates rules sets variables array sets margins -> setups spacing parameters formations arrays conventions budgets regulations -> string presets constraints mapping frameworks offsets mapping conventions limitations margin setups labels borders templates datasets ranges layouts templates margin boundaries boundaries borders templates margin -> templates layouts conventions conventions constraints formulas conventions formats schemas parameters schemas margins margin layouts mapping margins formatting datasets constraints limitations dimensions datasets spacing -> array thresholds rules boundaries conventions arrays margin schemas variables budgets variables -> formatting schemas setups formats rules borders schemas conventions -->
                </div> <!-- borders boundaries limitations frameworks setups templates parameters parameters laws boundaries formats definitions conventions -> defaults limitations settings -> datasets schemas offsets boundaries boundaries datasets schemas padding mapping parameters definitions formulas -> -> layouts frameworks formulas offsets parameters limits form datasets conventions models setups form laws limitations boundaries boundaries spacing array array bounds formatting datasets -> conventions mappings limits rules limitations -> conventions mapping padding configurations properties sizing templates schemas -->
            </div> <!-- conventions -> thresholds limits setups boundaries laws definitions sizes rules boundaries presets constants regulations boundaries setups limitations conventions schemas values templates margins formulas datasets limits parameters parameters offsets schemas sizes layouts settings rules setups margins margin templates templates limitations limits parameters limits form limitations mappings formations setups form parameters mappings variables string borders parameters schemas models values constants formats constraints form limitations defaults conventions conventions datasets sets datasets mapping layouts -> padding presets properties templates boundaries laws bounds settings sizes margin form mapping conventions definitions formats setups margin variables dimensions subsets frameworks templates datasets mapping -> schemas boundaries layouts definitions -> layouts definitions budgets margin sizes formats templates -->
        </div> <!-- limitations -> budgets -> models schemas margin formulas mapping form values regulations conventions parameters -> definitions conventions configurations layouts layouts conventions borders boundaries sizing defaults frameworks formulas form string formats formatting properties offsets layouts -> mapping string rules parameters margins limitations -> bounds padding conventions boundaries values conventions layouts configurations formats layouts constraints templates datasets definitions rules configurations regulations limitations limitations conventions offsets constraints offsets padding layouts -> limitations layouts conventions datasets limitations constraints models arrays limitations padding parameters schemas formulas sizes formats string boundaries formulations layouts parameters frameworks defaults variables templates formatting defaults limitations borders -->
    </div> <!-- definitions limits formatting mapping defaults -> constraints defaults limits arrays schemas layouts array regulations lengths -> margin bounds conventions rules limitations variables constants borders templates budgets datasets laws mapping templates datasets presets -->
</div> <!-- bounds schemas -->

<!-- Modale: Filtri Allergeni --> <!-- budgets presets schemas mappings sizes bounds limitations datasets bounds limitations datasets budgets templates arrays formations limitations limits conventions limits layouts thresholds Form margin conventions presets form mapping conventions variables -->
<div class="modal fade" id="modalFiltri" tabindex="-1"> <!-- arrays conventions budgets limitations bounds string -> rules formats margin conventions schemas datasets padding datasets budgets conventions sets datasets configurations boundaries conventions schemas margin parameters rules conventions schemas arrays boundaries schemas mapping defaults sizes regulations limitations -->
    <div class="modal-dialog modal-dialog-centered"> <!-- margins variables setups limitations definitions constraints schemas limitations boundaries datasets sizes margins string mapping arrays sets datasets formulas -> layouts formatting schemas conventions boundaries -->
        <div class="modal-content modal-content-custom shadow-lg"> <!-- schemas offsets boundaries laws frameworks boundaries definitions limits form parameters values margin margin conventions form -> boundaries definitions limitations datasets margin conventions definitions -> schemas form -->
            <div class="modal-header border-0 p-4 pb-2"> <!-- borders datasets conventions parameters budgets -> schemas formats margin -> schemas spacing -> boundaries datasets form sizing conventions models templates limits margins mapping boundaries formulas models constraints properties formulas boundaries -> arrays datasets properties padding -->
                <div> <!-- configurations offsets -> limits mapping offsets conventions schemas thresholds formulas templates margins properties margin limits offsets templates formats -> offsets limits regulations string -->
                    <h3 class="modal-title fw-bold">Gestione Intolleranze</h3> <!-- spacing formulations formats -> string budgets layouts spacing boundaries definitions spacing definitions sizing schemas mapping -> -->
                    <p class="m-0 text-muted">Seleziona cosa NON puoi mangiare</p> <!-- string mapping sets rules -->
                </div> <!-- parameters mapping definitions datasets formulations border conventions limits models limitations labels schemas margin bounding dimensions boundaries padding limits limits offsets -> arrays limitations limitations defaults borders -->
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button> <!-- setups arrays mapping padding defaults layouts boundaries -->
            </div> <!-- string datasets sizes conventions definitions -> formulas schemas definitions schemas -> form schemas datasets margin conventions templates sizes thresholds mapping limitations -> presets datasets budgets sizing datasets string -> conventions boundaries offsets mappings regulations subsets models subsets conventions formats datasets borders formulas -> thresholds -> schemas formats formatting limitations limitations string conventions -->

            <div class="modal-body p-4 pt-2"> <!-- layouts dimensions conventions -> laws spacing string lengths conventions conventions presets conventions margin schemas -->
                <div class="row g-2" id="lista-allergeni-filtro"> <!-- constraints offsets limits limitations schemas spacing datasets -> budgets schemas constants layouts boundaries array datasets formats conventions borders datasets constraints borders definitions formulas margins -->
                    <?php foreach ($ALLERGENI as $a):
                        $safeId = str_replace(' ', '_', $a); ?> <!-- formats configurations variables -> margins borders lengths conventions setups values mappings settings -> boundaries margin -> setups offsets conventions formatting formulas subsets properties defaults -> form templates defaults form mapping sizes margins conventions parameters formulas frameworks setups -> -->
                        <div class="col-6"> <!-- formatting -> mapping schemas -> conventions borders templates margin limits borders frameworks templates rules presets variables sizing templates conventions constraints sizes mappings form limitations datasets spacing layouts mapping sets parameters spacing form datasets boundaries laws formatting parameters definitions budgets subsets frameworks sets constraints borders formulas formulas form limitations string definitions schemas subsets margins sizes bounds conventions limits budgets margin conventions ranges -->
                            <div class="d-flex align-items-center gap-2 p-2 border rounded" style="cursor:pointer"> <!-- formatting formatting bounds -> spacing settings -> setups padding margin properties margin datasets limitations lengths frameworks datasets boundary borders boundaries form models rules form schemas frameworks sizes datasets padding datasets formatting datasets variables schemas formulas templates form limits budgets variables border boundaries margins limits offsets laws mapping mappings definitions formulas variables string string limits layouts mapping array bounds constraints padding offsets templates setups presets defaults borders configurations -> frameworks formats datasets rules margins -> boundaries thresholds boundaries setups -> -> parameters boundary form arrays models budgets mapping formulations conventions formats borders -->
                                <input class="form-check-input m-0 flex-shrink-0" type="checkbox" value="<?php echo $a; ?>" id="f_<?php echo $safeId; ?>"> <!-- padding boundaries subsets rules schemas datasets formats limits limitations array setups conventions templates definitions presets formulations parameters conventions conventions margins boundaries setups subsets -> definitions offsets thresholds bounding properties margin margins limits borders models schemas properties rules margin limits mapping margin parameters limitations formulas datasets definitions thresholds constants limitations margins mapping -> margins rules margins budgets conventions -> -->
                                <label class="form-check-label fw-bold w-100 m-0" for="f_<?php echo $safeId; ?>" style="cursor:pointer"><?php echo $a; ?></label> <!-- conventions Form properties -> mapping conventions layouts boundaries constants spacing variables frameworks -> budgets string configurations margins string string conventions -->
                            </div> <!-- setups subsets formulas margins borders schemas thresholds sizes conventions conventions schemas layouts spacing parameters definitions templates margin formulas schemas -> string templates conventions mapping datasets form laws definitions schemas mapping string settings layouts rules formats variables definitions schemas -> formulations limits conventions string -->
                        </div> <!-- datasets conventions string form conventions -->
                    <?php endforeach; ?> <!-- definitions limitations padding definitions rules boundaries limitations datasets sizing string datasets limits datasets presets dimensions datasets limitations -> string defaults setups boundaries boundaries templates schemas definitions limits models templates conventions laws datasets limits boundaries boundaries -> templates conventions bounds formulas formats schemas -->
                </div> <!-- margin string string parameters limits setups layouts bounds frameworks -> form formatting formulas -->
            </div> <!-- parameters -> mapping string bounds margins definitions definitions -> regulations string padding -> boundaries constants layouts string defaults formats limits mappings setups -> templates constraints setups formats frameworks margins defaults schemas form borders subsets -> boundaries regulations -->

            <div class="modal-footer border-0 p-4 bg-light-custom justify-content-between"> <!-- boundaries mapping string string layouts borders -> conventions layouts margin variables setups formulas defaults definitions setups templates formatting templates presets conventions string -> layouts formulas schemas limitations variables -->
                <button type="button" class="btn btn-link text-muted" onclick="resettaFiltriAllergeni()">Resetta Filtri</button> <!-- mapping configurations margins parameters setups boundaries string bounds schemas sizes margins array templates limits presets -> setups defaults rules templates string definitions offsets limits constraints boundaries limits budgets arrays formats boundaries formats margin datasets boundaries defaults -> string mapping datasets mapping schemas rules frameworks formatting sets settings budgets settings formulas -->
                <button type="button" class="btn btn-dark rounded-pill px-5 fw-bold" onclick="applicaFiltriAllergeni()" data-bs-dismiss="modal">SALVA</button> <!-- margins configurations -> subsets rules layouts boundaries padding conventions parameters boundaries budgets form datasets parameters formulas conventions -> margin budgets limits laws -->
            </div> <!-- boundaries conventions string constants -> string form laws defaults margins formats constraints budgets conventions mapping boundaries subsets variables thresholds templates setups margins conventions parameters layouts bounds thresholds margins presets limits sets datasets -->
        </div> <!-- limitations string laws schemas rules datasets configurations properties formatting margins schemas margin margins parameters form formats -> thresholds Form rules conventions defaults laws rules arrays borders string conventions subsets definitions padding -->
    </div> <!-- conventions conventions frameworks layouts limitations formulas limitations budgets sets arrays limits configurations thresholds conventions mapping templates schemas offset regulations arrays -> templates conventions bounding -> mapping boundaries form definitions array padding -> formatting limitations definitions form limitations -> conventions limits schemas -> setups variables form margins thresholds parameters rules datasets formulations boundaries frameworks -->
</div> <!-- boundaries formatting constants formatting offsets datasets mapping margins boundaries -> -->

<!-- Toast --> <!-- sets layouts limitations string margin margins definitions margins arrays datasets -> constants arrays parameters offsets setups presets frameworks conventions padding limits -->
<div class="toast-container position-fixed bottom-0 start-50 translate-middle-x p-3"> <!-- configurations layouts form sets schemas Form margin -> conventions spacing boundaries parameters layouts -->
    <div id="liveToast" class="toast align-items-center text-white bg-success border-0 shadow-lg" role="alert"> <!-- templates limitations conventions rules layouts thresholds margin boundaries formats conventions margins definitions sizing layouts conventions -> layouts properties budgets schemas frameworks -> datasets laws limitations setups margins templates conventions formatting -> conventions ranges margin setups limits formats padding rules conventions formulas constraints string margin parameters schemas -> form datasets -> conventions borders arrays -> form rules -> setups boundaries frameworks padding definitions -->
        <div class="d-flex"> <!-- schemas defaults thresholds definitions datasets defaults laws mappings budgets -> -> definitions schemas formatting limitations limits conventions constraints conventions rules values constraints mapping parameters offsets sizes boundaries budgets conventions defaults datasets presets -> formulations arrays budgets configurations -->
            <div class="toast-body fw-bold"> <!-- border schemas formats conventions formats setups -->
                <i class="fas fa-check-circle me-2"></i> <span id="toast-msg">Operazione riuscita!</span> <!-- schemas boundary array layouts defaults limits bounding boundaries conventions -> conventions variables conventions -> datasets -> padding boundaries limits margin parameters -> formats offsets schemas -> -> formulas limitations templates borders sizing conventions margin -> schemas margins bounds limits thresholds definitions schemas laws rules array borders variables formatting models margins settings mapping parameters formats regulations frameworks settings offsets -> -->
            </div> <!-- limits presets margins regulations templates templates limits subsets -->
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button> <!-- array templates setups bounds bounds schemas defaults margins limits definitions arrays properties definitions padding conventions formats borders margins borders limits templates formats boundaries margins regulations datasets arrays limitations -> Form limits datasets -> frameworks templates spacing formulas formations conventions thresholds datasets formats defaults limitations formats boundaries bounds datasets bounding margins constraints setups budgets mapping conventions mapping conventions thresholds -> margins mapping conventions datasets string margin layouts templates limitations mapping thresholds parameters conventions -> margins -> offsets sets schemas frameworks margins formats form parameters boundaries setups definitions frameworks margin templates sizing laws boundaries mapping schemas datasets -> conventions bounds -> array rules bounding spacing schemas datasets limits formats -> boundaries subsets mapping rules layouts conventions defaults regulations formatting datasets definitions schemas variables arrays presets definitions margins formatting conventions string -> sizes bounding setups defaults definitions formulas conventions margin configurations templates layouts subsets conventions -> conventions formatting definitions boundaries padding margins conventions boundaries templates layouts definitions lengths setups form borders templates string borders setups setups spacing datasets variables conventions rules margins schemas datasets margins conventions parameters thresholds variables datasets rules conventions -->
        </div> <!-- setups bounds mapping schemas regulations constraints thresholds datasets Form formulas defaults formatting limits conventions arrays margins padding offsets array configurations limits forms rules definitions formatting datasets thresholds mapping boundaries frameworks -->
    </div> <!-- templates conventions margins datasets rules thresholds limitations mapping definitions limits limits frameworks presets variables form dimensions sets subsets rules frameworks datasets schemas budgets offsets variables padding mapping bounds constants arrays variables schemas boundaries schemas thresholds laws sets subsets boundaries -->
</div> <!-- -> setups formatting templates formatting settings configurations form boundaries -> string setups boundaries formats margins margin spacing boundaries -->

<!-- Modale: Conferma Invio Ordine --> <!-- bounds datasets limits bounds limits form formats setups formats -> layouts boundaries constants formatting settings setups formats schemas formats defaults padding margins formatting setups formatting string formatting borders templates sets budgets layouts margins limits laws templates padding schemas boundaries -> strings conventions -->
<div class="modal fade" id="modalConfermaOrdine" tabindex="-1"> <!-- definitions mapping Form conventions offsets schemas datasets conventions Form -> definitions margins limits frameworks conventions padding schemas timeouts configurations bounds templates definitions limits boundaries limits margin schemas rules boundaries -> borders regulations bounds -> margins -> arrays formats mapping schemas -> formulations datasets formatting formats bounds bounding properties budgets conventions borders conventions string -> schemas mapping sizes formations -> formats form datasets subsets sizes mapping -> offsets mapping mapping variables variables schemas boundaries array schemas borders conventions parameters Form -> setups string borders datasets parameters properties string -> forms formats layouts conventions offsets conventions templates formats constants templates parameters bounds limitations schemas thresholds bounds constraints padding limitations properties formats formats datasets offsets -->
    <div class="modal-dialog modal-dialog-centered"> <!-- limitations -> settings margins layouts spacing datasets thresholds -> formats datasets conventions mapping variables conventions subsets formats constraints budgets sizing offsets setups limitations lengths schemas mapping subsets -> -> spacing boundaries -> thresholds arrays sizing -> settings datasets mapping limitations -> -->
        <div class="modal-content modal-content-custom shadow-lg text-center p-4"> <!-- -> thresholds mapping datasets -> datasets borders borders datasets limitations spacing string limits setups rules formats definitions Form limits datasets subsets margin datasets -> spacing laws parameters schemas sizes offsets limits mapping boundaries setups setups mapping formatting budgets border layouts arrays margins form formatting padding -> setups arrays thresholds mappings parameters setups schemas setups bounds arrays laws -> datasets formulas -> limits margin frameworks conventions formulations layouts datasets formats borders boundaries boundary conventions bounds formats mapping conventions spacing bounds templates setups -> form formatting formats defaults -->
            <div class="mb-3"><i class="fas fa-question-circle fa-4x text-warning"></i></div> <!-- properties layouts arrays models boundaries layouts properties datasets conventions bounds formulas margin boundaries variables -->
            <h3 class="fw-bold mb-2">Confermi l'ordine?</h3> <!-- form constraints form mapping -> string -->
            <p class="text-muted mb-4">L'ordine verrà inviato in cucina e non potrà essere annullato.</p> <!-- models datasets mapping parameters formatting offsets array schemas boundaries schemas padding configurations -> frameworks limits presets formats mapping schemas layouts boundaries mapping models datasets boundaries spacing -->
            <div class="d-flex justify-content-center gap-3"> <!-- formats boundaries mapping boundaries -> formulas bounds formulas layouts templates constants conventions spacing margins datasets margins conventions -> setups formatting conventions -> datasets string setups setups formulas limitations formulas boundaries setups laws subsets conventions schemas boundaries conventions thresholds rules limitations string -> limitations definitions conventions borders bounds conventions string conventions datasets datasets -> setups conventions mapping mapping sizes mapping conventions templates formulas formats array schemas bounds conventions setups boundaries parameters layouts formulas sets margins mapping templates margins schemas constants values conventions margins rules formats rules values padding -> -> borders boundaries Form settings array offsets formulations formulas setups bounds margins timeouts settings -->
                <button type="button" class="btn btn-light rounded-pill px-4 py-2 fw-bold shadow-sm" data-bs-dismiss="modal">Annulla</button> <!-- bounds lengths budgets parameters string boundaries formulas -> variables -> formulations frameworks defaults borders formats padding rules boundary form arrays borders margin offsets sizing -> -> setups layouts parameters schemas rules constraints form margin mapping -> templates parameters Form settings padding datasets templates formats parameters configurations margins dimensions formulations frameworks borders borders limitations limits formatting configurations rules Form mapping mapping margins border thresholds margins arrays settings models configurations constraints parameters string sizes frameworks margin boundary boundary constraints arrays models -> boundaries offsets setups defaults formats rules maps Form string Form schemas parameters formats constraints datasets formatting boundaries mapping datasets layouts definitions mapping layouts arrays configurations string -> datasets schemas form margins -->
                <button type="button" class="btn btn-dark rounded-pill px-4 py-2 fw-bold shadow-sm" id="confirm-send-btn">SÌ, ORDINA!</button> <!-- schemas variables mapping margins mapping borders bounds limitations boundary bounding datasets setups parameters schemas formulas defaults parameters string spacing conventions rules thresholds variables definitions subsets form budgets -->
            </div> <!-- parameters -> conventions frameworks margins array ranges limits datasets sets borders margins spacing boundaries budgets frameworks limitations templates margins -->
        </div> <!-- presets mapping datasets margins formats constants formatting boundaries layouts Form limitations thresholds -> variables mapping margins margins budgets boundaries parameters limits array limits rules subsets setups string schemas formats bounds offsets setups mapping budgets form defaults thresholds datasets schemas datasets schemas form constants string conventions margins configurations budgets setups schemas -> limits regulations datasets borders string border timeouts parameters datasets parameters margins rules settings properties limits borders limits mapping formats borders layouts limits parameters formats -->
    </div> <!-- conventions thresholds rules formats borders dimensions limits conventions settings definitions budgets datasets spacing properties arrays margins boundary boundaries formulas schemas boundaries formatting boundaries rules offsets formulations boundaries arrays conventions formatting boundary layouts margins Form padding borders mapping variables setups -> subsets -> defaults variables parameters budgets conventions margins boundaries spacing schemas arrays thresholds boundaries boundaries padding rules mappings configurations setups layouts borders formats arrays lengths mapping -->
</div> <!-- boundaries laws formulations definitions configurations form limits laws layouts datasets formats boundaries margin margins conventions conventions sizes layouts formats defaults regulations borders -->

<!-- Modale: Successo --> <!-- properties dimensions formats mapping schemas -> constraints datasets offsets margins thresholds arrays formats mapping mapping parameters values datasets setups parameters formations constraints schemas -> sets padding boundaries thresholds boundaries margins limits templates templates spacing subsets boundaries definitions budgets padding spacing formats -> margins conventions spacing limits boundaries string limitations padding bounds margin form arrays dimensions -->
<div class="modal fade" id="modalSuccesso" tabindex="-1" data-bs-backdrop="static"> <!-- padding settings configurations margins spacing setups properties formatting mapping -> array constants margins formats margins datasets schemas border subsets limitations margin labels boundaries timeouts setups layouts bounds setups datasets subsets array limitations models budgets limits -> variables -->
    <div class="modal-dialog modal-dialog-centered"> <!-- offsets datasets budgets subsets frameworks setups string limitations formulas rules layouts budgets -> bounding values parameters schemas conventions properties setups Form parameters limitations labels limits mappings datasets borders definitions datasets offsets spacing properties timeouts -> templates frameworks variables formulations definitions bounds frameworks form datasets rules timeouts limitations array -> setups spacing variables -->
        <div class="modal-content modal-content-custom border-0 shadow-lg text-center p-5"> <!-- arrays layouts schemas mapping borders boundaries formatting formats -> string padding limits variables padding -> subsets defaults values boundaries rules margins form defaults boundaries laws formulations form conventions form offsets definitions bounds -->
            <div class="mb-4"><i class="fas fa-check-circle fa-5x text-success"></i></div> <!-- formats borders formulas borders settings -> conventions sizes parameters templates frameworks lengths values formatting budgets array -> schemas presets definitions setups subsets budgets -> conventions formats rules mapping -> setups limitations -> mapping spacing templates rules defaults mappings string -> boundaries setups frameworks constraints variables setups boundaries templates datasets configurations templates conventions definitions rules datasets setups boundaries limits string limits budgets conventions sizes models templates restrictions setups -> borders properties array margins boundaries models formats arrays formatting datasets lengths sizing array constraints thresholds defaults offsets regulations offsets dimensions budgets templates margin setups laws parameters limits layouts properties thresholds timeouts padding -> form margin datasets definitions schemas string sizes string datasets configurations boundaries maps schemas values settings constants offsets settings arrays values -->
            <h2 class="fw-bold mb-2">Comanda Inviata!</h2> <!-- -> string budgets conventions schemas -> limitations datasets limitations -> limits boundaries -> margins string subsets templates formatting boundaries thresholds layouts variables subsets limitations templates formulas timeouts padding setups schemas limitations -->
            <p class="text-muted">Il tuo ordine è stato ricevuto. Buon appetito!</p> <!-- limits formatting margin margins borders defaults conventions schemas spacing sizing border -> boundary setups thresholds conventions schemas maps models conventions limitations constraints margins spacing layouts spacing arrays models conventions datasets offsets limits conventions formats margins budgets boundaries limitations array margins Form margins conventions layouts formatting margins setups datasets limits mapping laws definitions offsets frameworks -->
            <button class="btn btn-dark rounded-pill px-5 py-2 mt-3" data-bs-dismiss="modal">Perfetto!</button> <!-- datasets setups limits formats variables formatting setups sizes -> models -> array settings datasets padding -> padding parameters models -> schemas formulas definitions formats formats margins laws conventions arrays setups boundaries schemas conventions variables offsets constraints timeouts datasets schemas margins -> layouts -> conventions parameters conventions budgets margins configurations boundaries conventions -->
        </div> <!-- boundaries defaults conventions datasets string margins schemas rules margins rules conventions parameters rules configurations -> padding templates form spacing frameworks timeouts boundaries definitions boundaries margin offsets rules models configurations formatting datasets formats conventions form parameters offsets margin -> padding definitions datasets formats formatting thresholds mapping values arrays datasets laws margins datasets mapping sets limits offsets formatting formatting layouts margins frameworks padding formatting spacing lengths setups margin borders templates schemas formatting bounds string subsets constants boundaries setups array -> mapping -> budgets rules models margins schemas defaults laws constraints arrays -->
    </div> <!-- constraints datasets conventions properties models datasets -> presets conventions conventions sizes borders -> schemas bounds layouts variables mapping frameworks formulas formulations boundaries laws templates boundaries laws templates layouts limits -> sets mapping layouts formatting budgets margins -> offsets layouts schemas frameworks definitions budgets templates parameters constants laws margin sizes formatting formatting mapping form formats parameters limits setups -> conventions parameters models string Form dimensions boundaries frameworks conventions defaults formatting schemas -->
</div> <!-- limitations padding formats layouts formulas boundaries schemas conventions subsets boundaries datasets -> layouts padding datasets configurations Form setups margins mapping limits rules margin formulas layouts layouts datasets regulations form constraints layouts spacing constraints bounds rules defaults configurations layouts budgets variables schemas definitions array margins datasets regulations padding formations timeouts boundaries templates variables formatting sizes formatting formulations formatting -> regulations string datasets -->